version: "3.3"

services:
  db:
    image: mariadb
    volumes:
      - ./mywebsite/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_PASSWORD: root

  phpadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 300000000

  wordpress:
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID}
    depends_on:
      - db
    volumes:
      - ./mywebsite/wp:/var/www/html
    image: wordpress:latest

    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db
volumes:
  db_data:
